# Generated by Django 5.0.6 on 2024-06-10 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('Update_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Update_desc', models.CharField(max_length=100)),
                ('TimeStamp', models.DateField(auto_now_add=True)),
                ('order_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
            ],
        ),
    ]
